// rolink-extension/core/code-fields.js — GENERATED. Do not edit by hand.
// Re-emit with: node scripts/emit-code-fields.js
//
// Source of truth: generated/code-fields.json (regenerated by
// `npm run generate:code-fields`).
//
// Loaded by the content scripts (see rolink-extension/manifest.json) BEFORE
// core/parser.js so parser.js can dynamically accept ###RAW:<field>### for any
// string field declared in any tool's Zod inputSchema.
window.ROLINK_CODE_FIELDS = {
  "version": 2,
  "source": "mcp-server/src/tools/registry.ts",
  "generatedAt": "2026-09-02T12:20:58.726Z",
  "toolCount": 140,
  "toolFields": {
    "get_instances": [
      "path",
      "projectId"
    ],
    "create_instance": [
      "className",
      "name",
      "parent",
      "projectId"
    ],
    "set_properties": [
      "path",
      "projectId"
    ],
    "delete_instance": [
      "path",
      "projectId"
    ],
    "clone_instance": [
      "newName",
      "parent",
      "path",
      "projectId"
    ],
    "move_instance": [
      "newParent",
      "path",
      "projectId"
    ],
    "find_instance": [
      "projectId",
      "query"
    ],
    "execute_luau": [
      "code",
      "datamodel_type",
      "projectId",
      "studio_id"
    ],
    "get_script_content": [
      "path",
      "projectId"
    ],
    "set_script_content": [
      "content",
      "path",
      "projectId"
    ],
    "create_module": [
      "exports",
      "path",
      "projectId"
    ],
    "run_function": [
      "functionName",
      "path",
      "projectId"
    ],
    "add_event_handler": [
      "event",
      "handlerCode",
      "path",
      "projectId"
    ],
    "remove_event_handler": [
      "event",
      "path",
      "projectId"
    ],
    "get_global_variables": [
      "projectId"
    ],
    "take_snapshot": [
      "label",
      "projectId"
    ],
    "rollback": [
      "projectId",
      "snapshotId"
    ],
    "diff_snapshots": [
      "fromId",
      "projectId",
      "toId"
    ],
    "run_in_sandbox": [
      "code",
      "projectId"
    ],
    "confirm_sandbox_apply": [
      "projectId",
      "sandboxId"
    ],
    "discard_sandbox": [
      "projectId",
      "sandboxId"
    ],
    "simulate_ticks": [
      "projectId"
    ],
    "get_context_summary": [
      "projectId"
    ],
    "get_function_signatures": [
      "path",
      "projectId"
    ],
    "get_property_value": [
      "path",
      "projectId",
      "property"
    ],
    "get_all_properties": [
      "path",
      "projectId"
    ],
    "search_by_attribute": [
      "attribute",
      "projectId"
    ],
    "get_referenced_instances": [
      "path",
      "projectId"
    ],
    "resolve_path": [
      "path",
      "projectId"
    ],
    "ensure_path": [
      "path",
      "projectId"
    ],
    "get_dependency_graph": [
      "projectId"
    ],
    "suggest_ordering": [
      "projectId"
    ],
    "validate_command": [
      "tool"
    ],
    "get_performance_stats": [
      "projectId"
    ],
    "analyze_performance": [
      "code"
    ],
    "set_performance_threshold": [
      "projectId"
    ],
    "get_memory_usage": [
      "projectId"
    ],
    "generate_terrain": [
      "projectId"
    ],
    "set_terrain_region": [
      "material",
      "projectId"
    ],
    "place_parts": [
      "parent",
      "projectId"
    ],
    "create_model_from_table": [
      "name",
      "parent",
      "parts[].className",
      "projectId"
    ],
    "apply_material": [
      "material",
      "projectId",
      "region"
    ],
    "create_ui": [
      "name",
      "projectId"
    ],
    "set_ui_property": [
      "path",
      "projectId",
      "property"
    ],
    "get_ui_tree": [
      "projectId"
    ],
    "bind_ui_click": [
      "handlerCode",
      "path",
      "projectId"
    ],
    "create_animation_track": [
      "keyframes[].poses[].part",
      "name",
      "projectId"
    ],
    "play_animation": [
      "animationId",
      "characterPath",
      "projectId",
      "target"
    ],
    "set_lighting": [
      "projectId"
    ],
    "add_particle_emitter": [
      "path",
      "projectId"
    ],
    "setup_datastore": [
      "name",
      "projectId"
    ],
    "get_datastore_value": [
      "key",
      "projectId",
      "store"
    ],
    "set_datastore_value": [
      "key",
      "projectId",
      "store"
    ],
    "export_session_log": [
      "projectId"
    ],
    "replay_session": [
      "projectId",
      "sessionId"
    ],
    "list_sessions": [],
    "compare_sessions": [
      "a",
      "b"
    ],
    "list_templates": [
      "category"
    ],
    "apply_template": [
      "id",
      "projectId"
    ],
    "add_template": [
      "category",
      "code",
      "description",
      "id",
      "name"
    ],
    "get_time": [],
    "send_notification": [
      "message",
      "projectId"
    ],
    "batch_queue": [
      "commands[].tool",
      "projectId"
    ],
    "cancel_command": [
      "id"
    ],
    "train_model": [
      "projectId"
    ],
    "compile_visual_graph": [
      "projectId"
    ],
    "generate_test": [
      "code",
      "projectId"
    ],
    "run_tests": [
      "projectId"
    ],
    "session_users": [
      "projectId"
    ],
    "search_asset": [
      "category",
      "keyword"
    ],
    "import_asset": [
      "parent",
      "projectId"
    ],
    "report_metrics": [
      "projectId"
    ],
    "get_metrics": [
      "projectId"
    ],
    "git_commit": [
      "message"
    ],
    "git_log": [],
    "git_rollback": [
      "commit",
      "projectId"
    ],
    "predict_bug": [
      "code",
      "projectId"
    ],
    "plan_game": [
      "prompt"
    ],
    "execute_plan": [
      "projectId",
      "prompt"
    ],
    "review_code": [
      "code"
    ],
    "refactor_code": [
      "code",
      "projectId"
    ],
    "generate_asset": [
      "projectId",
      "prompt"
    ],
    "optimize_performance": [
      "projectId",
      "snapshot"
    ],
    "report_analytics": [
      "event",
      "projectId"
    ],
    "get_analytics": [
      "projectId"
    ],
    "suggest_design": [
      "projectId"
    ],
    "list_plugins": [],
    "load_plugin": [
      "code",
      "name"
    ],
    "set_breakpoint": [
      "condition",
      "path",
      "projectId"
    ],
    "remove_breakpoint": [
      "path",
      "projectId"
    ],
    "watch_variable": [
      "path",
      "projectId",
      "variable"
    ],
    "step_through": [
      "path",
      "projectId"
    ],
    "continue_execution": [
      "path",
      "projectId"
    ],
    "generate_level": [
      "projectId",
      "prompt"
    ],
    "get_projects": [],
    "switch_project": [
      "projectId"
    ],
    "create_project": [
      "projectId",
      "template"
    ],
    "get_suggestions": [
      "context",
      "projectId"
    ],
    "run_playtest": [
      "projectId"
    ],
    "export_project": [
      "projectId"
    ],
    "import_project": [
      "archive",
      "projectId"
    ],
    "generate_quest": [
      "difficulty",
      "projectId",
      "theme"
    ],
    "simulate_economy": [
      "projectId"
    ],
    "suggest_balance": [
      "projectId"
    ],
    "explain_code": [
      "code",
      "path",
      "projectId"
    ],
    "learning_mode": [
      "projectId"
    ],
    "adjust_difficulty": [
      "projectId"
    ],
    "set_difficulty_profile": [
      "projectId"
    ],
    "generate_sound": [
      "projectId",
      "prompt"
    ],
    "generate_sound_pack": [
      "prompt"
    ],
    "play_sound": [
      "path",
      "projectId",
      "soundId"
    ],
    "get_animation_info": [
      "animationId",
      "projectId"
    ],
    "delete_animation": [
      "animationId",
      "projectId"
    ],
    "create_cutscene": [
      "loop",
      "name",
      "projectId",
      "shots"
    ],
    "create_dialogue": [
      "lines",
      "npcPath",
      "projectId"
    ],
    "create_motion_effect": [
      "duration",
      "effect",
      "path",
      "projectId",
      "properties"
    ],
    "create_vfx": [
      "effect",
      "parent",
      "projectId",
      "properties"
    ],
    "export_animation_clip": [
      "animationId",
      "projectId",
      "trackPath"
    ],
    "publish_animation": [
      "action",
      "animationId",
      "assetId",
      "projectId",
      "trackPath"
    ],
    "scan_errors": [
      "projectId"
    ],
    "inspect_ui": [
      "root",
      "projectId"
    ],
    "screenshot_studio": [
      "projectId"
    ],
    "playtest_scenario": [
      "scenario",
      "watch",
      "expect",
      "projectId"
    ],
    "migrate_system": [
      "system",
      "goal",
      "sources[]",
      "projectId"
    ],
    "analyze_animatable_model": [
      "projectId",
      "target"
    ],
    "create_model_animation": [
      "confirm",
      "duration",
      "fps",
      "loop",
      "name",
      "projectId",
      "target"
    ],
    "set_model_keyframe": [
      "anim",
      "ease",
      "pose",
      "projectId",
      "t",
      "track"
    ],
    "set_model_easing": [
      "anim",
      "ease",
      "keyIndex",
      "projectId",
      "track"
    ],
    "add_animation_marker": [
      "anim",
      "event",
      "name",
      "projectId",
      "remove",
      "t"
    ],
    "preview_model_animation": [
      "anim",
      "projectId",
      "step"
    ],
    "validate_model_animation": [
      "anim",
      "projectId"
    ],
    "retime_animation": [
      "anim",
      "newName",
      "projectId",
      "scale"
    ],
    "reverse_animation": [
      "anim",
      "newName",
      "projectId"
    ],
    "mirror_animation": [
      "anim",
      "newName",
      "projectId",
      "swapPairs"
    ],
    "blend_animation": [
      "base",
      "newName",
      "overlay",
      "projectId",
      "weight"
    ],
    "fix_animation": [
      "anim",
      "projectId"
    ],
    "create_attack_animation": [
      "anticipation",
      "confirm",
      "duration",
      "fps",
      "impactT",
      "loop",
      "name",
      "projectId",
      "strike",
      "target",
      "tracks[]"
    ],
    "create_idle_animation": [
      "confirm",
      "duration",
      "fps",
      "loop",
      "name",
      "projectId",
      "sway",
      "target",
      "tracks[]"
    ],
    "create_walk_cycle": [
      "confirm",
      "duration",
      "fps",
      "loop",
      "name",
      "projectId",
      "stride",
      "target",
      "tracks[]"
    ],
    "set_track_lock": [
      "anim",
      "locked",
      "projectId",
      "track"
    ]
  },
  "stringFields": [
    "a",
    "action",
    "anim",
    "animationId",
    "anticipation",
    "archive",
    "assetId",
    "attribute",
    "b",
    "base",
    "category",
    "characterPath",
    "className",
    "code",
    "commit",
    "condition",
    "confirm",
    "content",
    "context",
    "datamodel_type",
    "description",
    "difficulty",
    "duration",
    "ease",
    "effect",
    "event",
    "expect",
    "exports",
    "fps",
    "fromId",
    "functionName",
    "goal",
    "handlerCode",
    "id",
    "impactT",
    "key",
    "keyIndex",
    "keyword",
    "label",
    "lines",
    "locked",
    "material",
    "message",
    "name",
    "newName",
    "newParent",
    "npcPath",
    "overlay",
    "parent",
    "part",
    "path",
    "pose",
    "projectId",
    "prompt",
    "property",
    "query",
    "region",
    "remove",
    "root",
    "sandboxId",
    "scale",
    "scenario",
    "sessionId",
    "shots",
    "snapshot",
    "snapshotId",
    "soundId",
    "sources",
    "step",
    "store",
    "stride",
    "strike",
    "studio_id",
    "swapPairs",
    "sway",
    "system",
    "t",
    "target",
    "template",
    "theme",
    "toId",
    "tool",
    "track",
    "trackPath",
    "tracks[]",
    "variable",
    "watch",
    "weight"
  ],
  "codeLikeFields": [
    "code",
    "content",
    "context",
    "description",
    "exports",
    "handlerCode",
    "label",
    "message",
    "prompt",
    "query"
  ]
};
