// SPDX-License-Identifier: GPL-3.0-or-later
// tests/dispatch.test.js — Phase 0 dispatch-safety gate.
//
// Verifies that EVERY registered tool (the 111 in
// mcp-server/src/tools/registry.ts) round-trips through the parser with a
// non-empty .tool field, and that the parser's normalised shape exposes the
// .name / .arguments aliases the agent loop relies on (catches the
// `c.name / c.arguments` typo that broke every tool call in production).
//
// Run: node tests/dispatch.test.js   (no deps)

const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

function loadParser() {
  const codeFields = fs.readFileSync(
    path.join(__dirname, "..", "rolink-extension", "core", "code-fields.js"),
    "utf8"
  );
  const parser = fs.readFileSync(
    path.join(__dirname, "..", "rolink-extension", "core", "parser.js"),
    "utf8"
  );
  const ctx = { window: {}, globalThis: {}, console };
  ctx.globalThis = ctx;
  vm.createContext(ctx);
  vm.runInContext(codeFields + "\n" + parser, ctx);
  return ctx.window.ZSParse;
}

function loadRegistry() {
  // The registry is TypeScript; this test uses a tiny ESM bridge that re-exports
  // the 111 tool names as a flat list. Generated by `scripts/list-tool-names.ts`
  // during CI and committed at `tests/__registry__.json`. If the file is
  // missing we fall back to enumerating the 111 hard-coded names from the
  // generated fixtures directory.
  const regPath = path.join(__dirname, "__registry__.json");
  if (fs.existsSync(regPath)) {
    return JSON.parse(fs.readFileSync(regPath, "utf8"));
  }
  const fxDir = path.join(__dirname, "..", "rolink-extension", "core", "__fixtures__", "tool-calls");
  return fs.readdirSync(fxDir)
    .filter(f => f.endsWith(".txt") && !f.startsWith("edge-") && f !== "README.txt")
    .map(f => f.replace(/\.txt$/, ""))
    .sort();
}

const ZSParse = loadParser();
const tools = loadRegistry();

let passed = 0, failed = 0;
function assert(cond, msg) { if (!cond) throw new Error("ASSERT FAILED: " + msg); }
function ok(name) { console.log("✓", name); passed++; }
function bad(name, e) { console.error("✗", name, e && e.message || ""); failed++; }

(async () => {
  // ── 1: aliases (the root cause) ─────────────────────────────────────
  await run("normalised call exposes .name / .arguments aliases", async () => {
    const blks = ZSParse.extractAll('###MCP_TOOL###\n{"tool":"create_instance","args":{"className":"Part"}}\n');
    assert(blks.length === 1, "one block");
    const c = blks[0];
    assert(c.tool === "create_instance", ".tool");
    assert(c.name === "create_instance", ".name alias");
    assert(c.args && c.args.className === "Part", ".args");
    assert(c.arguments && c.arguments.className === "Part", ".arguments alias");
  });

  // ── 2: 111-tool round trip with non-empty name ─────────────────────
  await run(`${tools.length} tools round-trip with non-empty name`, async () => {
    assert(tools.length >= 111, `expected >= 111 tools, found ${tools.length}`);
    for (const name of tools) {
      const fixture = `###MCP_TOOL###\n${JSON.stringify({ tool: name, args: {} })}`;
      const blks = ZSParse.extractAll(fixture);
      assert(blks.length >= 1, `${name}: no blocks extracted`);
      for (const c of blks) {
        assert(typeof c.tool === "string" && c.tool.length > 0, `${name}: empty .tool`);
        assert(c.name === c.tool, `${name}: .name alias must equal .tool`);
        assert(c.arguments === c.args, `${name}: .arguments alias must equal .args (same reference)`);
      }
    }
  });

  // ── 3: the specific bug — dispatch with .name/.arguments works ─────
  await run("dispatch signature: c.name and c.arguments are both populated", async () => {
    // This is the test that would have caught the v4.3.0 bug.
    const c = ZSParse.extractAll('###MCP_TOOL###\n{"tool":"execute_luau","args":{"code":"print(1)"}}')[0];
    // Pretend we are dispatchTool:
    function dispatchTool(name, args) {
      if (!name || typeof name !== "string") {
        return { ok: false, kind: "validation_error", error: "invalid tool name " + String(name) };
      }
      return { ok: true, tool: name, code: args && args.code };
    }
    const r1 = dispatchTool(c.name, c.arguments);
    const r2 = dispatchTool(c.tool, c.args);
    assert(r1.ok === true, "alias call must succeed");
    assert(r2.ok === true, "canonical call must succeed");
    assert(r1.tool === "execute_luau" && r1.code === "print(1)", "alias path");
    assert(r2.tool === "execute_luau" && r2.code === "print(1)", "canonical path");
  });

  // ── 4: never produces the undefined bug ────────────────────────────
  await run("never produces 'invalid tool name undefined'", async () => {
    for (const name of tools) {
      const fixture = `###MCP_TOOL###\n${JSON.stringify({ tool: name, args: { dummy: 1 } })}`;
      const calls = ZSParse.extractAll(fixture).filter(Boolean);
      for (const c of calls) {
        if (!c.tool || !c.name) {
          throw new Error(`${name}: produced a call without a .tool / .name`);
        }
      }
    }
  });

  // ── 5: 111-tool full Zod-derived sample round-trip (Phase 4) ─────
  // If tests/tool-samples.json exists, every tool's Zod-derived sample
  // args must round-trip the parser cleanly. This is the dispatch-safety
  // gate: the model can emit any shape the schema declares, and the
  // parser must give the agent loop a usable .tool + .args.
  await run(`${tools.length}-tool full Zod-sample round-trip`, async () => {
    const samplesPath = path.join(__dirname, "tool-samples.json");
    if (!fs.existsSync(samplesPath)) {
      console.log("  (skipped: tool-samples.json not present; run `npm run audit:tools`)");
      return;
    }
    const samples = JSON.parse(fs.readFileSync(samplesPath, "utf8"));
    for (const [name, args] of Object.entries(samples)) {
      const fixture = `###MCP_TOOL###\n${JSON.stringify({ tool: name, args })}`;
      const calls = ZSParse.extractAll(fixture).filter(Boolean);
      if (calls.length !== 1) {
        throw new Error(`${name}: expected 1 block, got ${calls.length}`);
      }
      const c = calls[0];
      if (c.tool !== name) {
        throw new Error(`${name}: parser returned .tool=${c.tool}`);
      }
      if (typeof c.args !== "object" || c.args === null) {
        throw new Error(`${name}: parser returned non-object .args`);
      }
    }
  });

  console.log(`\nDispatch tests: ${passed} passed, ${failed} failed`);
  if (failed) process.exit(1);

  async function run(name, fn) { try { await fn(); ok(name); } catch (e) { bad(name, e); } }
})();
