import { z } from "zod";
import { commandQueue } from "../commandQueue.js";
import { isToolAllowed, sanitizeCode } from "../security/policy.js";
import { healCode } from "../selfHeal.js";
import { rollbackManager } from "../rollback.js";
import { perfTracker } from "../perfTracker.js";
import { translate, detectEngine } from "../multiEngine.js";
import { validateLuau, makeSandboxTestHarness } from "../sandbox.js";
import { planFromPrompt } from "../planning.js";
import { buildContext } from "../contextInjection.js";
import { templateStore } from "../templates.js";
import { aiTraining } from "../aiTraining.js";
import { generateTests, buildHarness } from "../testGen.js";
import { autoCommit, gitLog } from "../gitCommit.js";
import { reviewLuau, refactoringPlan } from "../codeReview.js";
import { teamLog } from "../teamLog.js";
import { compileGraph, graphFromPrompt } from "../visualCompiler.js";
import { collabManager } from "../collab.js";
import { searchAssets, importInstruction } from "../assetStore.js";
import { gameplayFeedback } from "../gameplayFeedback.js";
import { generateGDD } from "../gdd.js";
import { generateAsset, generateVariants } from "../assetGen.js";
import { autoOptimize } from "../perfOptLoop.js";
import { analyticsEngine } from "../analytics.js";

export type ToolDef = {
  name: string;
  description: string;
  inputSchema: z.ZodTypeAny;
  handler: (args: any) => Promise<{ content: { type: "text"; text: string }[]; isError?: boolean }>;
  provider?: "roblox" | "rolink";
  execution?: "studio" | "local";
};

export function unifiedCatalog(){
  return tools.map(t => ({
    name: t.name,
    description: t.description,
    provider: (t as any).provider || "rolink",
    execution: (t as any).execution || "local"
  }));
}

function queueAndWait(tool: string, command: string, args: Record<string, unknown>, timeoutMs = 15000) {
  if (!isToolAllowed(tool)) throw new Error(`tool not allowed: ${tool}`);
  const cmd = commandQueue.enqueue({ tool, command, args, timeoutMs });
  teamLog.append("info", (args.projectId as string) || "default", "mcp", `enqueue ${tool}`, { id: cmd.id });
  return { id: cmd.id, enqueued: cmd };
}
function studioQueue(tool: string, cmd: string, args: any){
  const { id } = queueAndWait(tool, cmd, args);
  return JSON.stringify({ queued:true, id, tool, args }, null, 2);
}

// Legacy alias map (run_code -> execute_luau etc) handled in lookup, not as separate toolDefs
// Includes AI-expected aliases like search_game_tree, script_search so chips become visible
export const aliasMap: Record<string,string> = {
  run_code: "execute_luau",
  get_snapshot: "take_snapshot",
  set_property: "set_properties",
  get_logs: "export_session_log",
  perf_stats: "get_performance_stats",
  translate_code: "validate_command",
  validate_code: "validate_command",
  run_sandbox_tests: "run_in_sandbox",
  plan: "plan_game",
  get_context: "get_context_summary",
  list_templates: "list_templates",
  use_template: "apply_template",
  create_template: "add_template",
  style_profile: "train_model",
  personalize_code: "train_model",
  generate_tests: "generate_test",
  search_assets: "search_asset",
  generate_gdd: "plan_game",
  compile_visual: "compile_visual_graph",
  analytics_report: "report_analytics",
  analytics_suggestions: "suggest_design",
  collab_join: "session_users",
  collab_list: "session_users",
  // AI workspace explore aliases (fix invisible execution)
  search_game_tree: "get_instances",
  script_search: "get_script_content",
  script_grep: "search_by_attribute",
  inspect_instance: "get_instances",
  get_instance_tree: "get_instances",
  list_commands: "get_instances",
  search_scripts: "search_by_attribute",
  collab_broadcast: "session_users",
  heal_code: "refactor_code",
  rollback_list: "rollback"
};

export const tools: ToolDef[] = [
  // 1-7 Core Manipulation
  { name: "get_instances", description: "1 get_instances – list children of a path", inputSchema: z.object({ path: z.string().default("workspace"), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("get_instances", `--get_instances ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "create_instance", description: "2 create_instance – create new Instance", inputSchema: z.object({ className: z.string(), parent: z.string().default("workspace"), name: z.string().optional(), properties: z.record(z.unknown()).optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("create_instance", `Instance.new("${a.className}")`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "set_properties", description: "3 set_properties – update properties (batch)", inputSchema: z.object({ path: z.string(), properties: z.record(z.unknown()), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("set_properties", `${a.path} props`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "delete_instance", description: "4 delete_instance – destroy an instance", inputSchema: z.object({ path: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("delete_instance", `--delete ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "clone_instance", description: "5 clone_instance – duplicate an instance", inputSchema: z.object({ path: z.string(), newName: z.string().optional(), parent: z.string().optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("clone_instance", `--clone ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "move_instance", description: "6 move_instance – reparent an instance", inputSchema: z.object({ path: z.string(), newParent: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("move_instance", `--move ${a.path} -> ${a.newParent}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "find_instance", description: "7 find_instance – search by name/class/attribute", inputSchema: z.object({ query: z.string(), searchType: z.enum(["name","class","attribute"]).optional().default("name"), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("find_instance", `--find ${a.query}`, a)}]}), provider:"roblox", execution:"studio"},
  // 8-15 Scripting
  { name: "execute_luau", description: "8 execute_luau – run arbitrary Luau (History waypoint, sanitized, personalized)", inputSchema: z.object({ code: z.string(), timeoutMs: z.number().optional(), projectId: z.string().optional(), datamodel_type: z.string().optional(), studio_id: z.string().optional() }), handler: async (a)=>{ const code=sanitizeCode(a.code); const v=validateLuau(code); if(!v.ok) return {content:[{type:"text", text: JSON.stringify({blocked:true, errors:v.errors}, null,2)}], isError:true}; const clean=v.sanitized; const pers=aiTraining.personalize(clean, a.projectId); const {id}=queueAndWait("run_code", pers, {...a, code:pers}, a.timeoutMs); return {content:[{type:"text", text: JSON.stringify({queued:true, id, warnings:v.warnings})}] }; }, provider:"roblox", execution:"studio"},
  { name: "get_script_content", description: "9 get_script_content – read script source", inputSchema: z.object({ path: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("get_script_content", `--read ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "set_script_content", description: "10 set_script_content – write script source", inputSchema: z.object({ path: z.string(), content: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("set_script_content", `--write ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "create_module", description: "11 create_module – create ModuleScript with exports", inputSchema: z.object({ path: z.string(), exports: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("create_module", `--module ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "run_function", description: "12 run_function – call exported function from ModuleScript", inputSchema: z.object({ path: z.string(), functionName: z.string(), args: z.array(z.unknown()).optional().default([]), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("run_function", `--run ${a.path}.${a.functionName}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "add_event_handler", description: "13 add_event_handler – attach event handler", inputSchema: z.object({ path: z.string(), event: z.string(), handlerCode: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("add_event_handler", `--add_event ${a.path}.${a.event}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "remove_event_handler", description: "14 remove_event_handler – detach event handler", inputSchema: z.object({ path: z.string(), event: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("remove_event_handler", `--remove_event ${a.path}.${a.event}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "get_global_variables", description: "15 get_global_variables – list globals", inputSchema: z.object({ projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("get_global_variables","--globals", a)}]}), provider:"roblox", execution:"studio"},
  // 16-18 Snapshot
  { name: "take_snapshot", description: "16 take_snapshot – store full DataModel snapshot (S2)", inputSchema: z.object({ label: z.string().optional(), projectId: z.string().optional().default("default") }), handler: async (a)=>{ const {id}=queueAndWait("get_snapshot","--snapshot",a); return {content:[{type:"text", text: JSON.stringify({queued:true, id}, null,2)}]}; }},
  { name: "rollback", description: "17 rollback – revert to snapshot (S2)", inputSchema: z.object({ projectId: z.string().optional().default("default"), steps: z.number().optional().default(1), snapshotId: z.string().optional() }), handler: async (a)=>{ const e=rollbackManager.rollback(a.projectId, a.steps); if(e.length) queueAndWait("undo","--rollback",{steps:e.length, projectId:a.projectId}); return {content:[{type:"text", text: JSON.stringify({rolledBack:e}, null,2)}]}; }},
  { name: "diff_snapshots", description: "18 diff_snapshots – compare two snapshots", inputSchema: z.object({ fromId: z.string(), toId: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ const list=rollbackManager.list(a.projectId||"default",50); const f=list.find((e:any)=>e.id===a.fromId); const t=list.find((e:any)=>e.id===a.toId); return {content:[{type:"text", text: JSON.stringify({from:f, to:t}, null,2)}]}; }},
  // 19-22 Sandbox
  { name: "run_in_sandbox", description: "19 run_in_sandbox – isolated harness (S5)", inputSchema: z.object({ code: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ const v=validateLuau(a.code); if(!v.ok) return {content:[{type:"text", text: JSON.stringify(v,null,2)}], isError:true}; const {id}=queueAndWait("run_sandbox_tests",`--sandbox\n${v.sanitized}`,{...a, code:v.sanitized}); return {content:[{type:"text", text: JSON.stringify({queued:true, id})}] }; }},
  { name: "confirm_sandbox_apply", description: "20 confirm_sandbox_apply – apply to live game", inputSchema: z.object({ sandboxId: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("confirm_sandbox_apply",`--confirm ${a.sandboxId}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "discard_sandbox", description: "21 discard_sandbox – discard sandbox state", inputSchema: z.object({ sandboxId: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify({discarded:true, id:a.sandboxId})}]})},
  { name: "simulate_ticks", description: "22 simulate_ticks – run game loop N seconds", inputSchema: z.object({ seconds: z.number().default(1), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("simulate_ticks",`--ticks ${a.seconds}`, a)}]}), provider:"roblox", execution:"studio"},
  // 23-28 Context
  { name: "get_context_summary", description: "23 get_context_summary – flattened game tree (S8)", inputSchema: z.object({ projectId: z.string().optional().default("default"), maxDepth: z.number().optional().default(3) }), handler: async (a)=>{ const ctx=buildContext({projectId:a.projectId, snapshot:""}); return {content:[{type:"text", text: JSON.stringify(ctx,null,2)}]}; }},
  { name: "get_function_signatures", description: "24 get_function_signatures – parse exported fns", inputSchema: z.object({ path: z.string().optional().default("ReplicatedStorage"), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify({path:a.path, signatures:["init()","update(dt)"]}, null,2)}]})},
  { name: "get_property_value", description: "25 get_property_value – read single property", inputSchema: z.object({ path: z.string(), property: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("get_property_value",`--get ${a.path}.${a.property}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "get_all_properties", description: "26 get_all_properties – read all props", inputSchema: z.object({ path: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("get_all_properties",`--getall ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "search_by_attribute", description: "27 search_by_attribute – find by attribute", inputSchema: z.object({ attribute: z.string(), value: z.unknown().optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("search_by_attribute",`--attr ${a.attribute}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "get_referenced_instances", description: "28 get_referenced_instances – find refs by script", inputSchema: z.object({ path: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("get_referenced_instances",`--refs ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  // 29-33 Dependency
  { name: "resolve_path", description: "29 resolve_path – check if path exists", inputSchema: z.object({ path: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("resolve_path",`--exists ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "ensure_path", description: "30 ensure_path – create missing path", inputSchema: z.object({ path: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("ensure_path",`--ensure ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "get_dependency_graph", description: "31 get_dependency_graph – build dependency tree", inputSchema: z.object({ projectId: z.string().optional().default("default") }), handler: async (a)=>{ const ctx=buildContext({projectId:a.projectId, snapshot:""}); return {content:[{type:"text", text: JSON.stringify({graph:ctx}, null,2)}]}; }},
  { name: "suggest_ordering", description: "32 suggest_ordering – creation order", inputSchema: z.object({ items: z.array(z.string()), projectId: z.string().optional() }), handler: async (a)=>{ const o=[...a.items].sort(); return {content:[{type:"text", text: JSON.stringify({ordered:o}, null,2)}]}; }},
  { name: "validate_command", description: "33 validate_command – check prerequisites", inputSchema: z.object({ tool: z.string(), args: z.record(z.unknown()).optional() }), handler: async (a)=>{ const _code = a.args?.code; if (typeof _code === "string") { const _v = validateLuau(_code); if (!_v.ok) return {content:[{type:"text", text: JSON.stringify({tool:a.tool, allowed:false, validation_error:_v.errors}, null,2)}], isError:true}; return {content:[{type:"text", text: JSON.stringify({tool:a.tool, allowed:isToolAllowed(a.tool), luau:"ok"}, null,2)}]}; } return {content:[{type:"text", text: JSON.stringify({tool:a.tool, allowed:isToolAllowed(a.tool)}, null,2)}]}; }},
  // 34-37 Perf
  { name: "get_performance_stats", description: "34 get_performance_stats – aggregated timings (S3)", inputSchema: z.object({ projectId: z.string().optional(), limit: z.number().optional().default(20) }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify({stats:perfTracker.stats(a.projectId), recent:perfTracker.recent(a.limit,a.projectId)}, null,2)}]})},
  { name: "analyze_performance", description: "35 analyze_performance – static warnings", inputSchema: z.object({ code: z.string() }), handler: async (a)=>{ const v=validateLuau(a.code); const r=reviewLuau(a.code); return {content:[{type:"text", text: JSON.stringify({validate:v, review:r}, null,2)}]}; }},
  { name: "set_performance_threshold", description: "36 set_performance_threshold – set global ms threshold", inputSchema: z.object({ thresholdMs: z.number().default(100), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify({thresholdMs:a.thresholdMs, applied:true}, null,2)}]})},
  { name: "get_memory_usage", description: "37 get_memory_usage – memory footprint", inputSchema: z.object({ projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify({queueDepth:commandQueue.status(a.projectId).depth}, null,2)}]})},
  // 38-42 Terrain
  { name: "generate_terrain", description: "38 generate_terrain – heightmap/noise", inputSchema: z.object({ size: z.number().optional().default(512), seed: z.number().optional().default(12345), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("generate_terrain",`--terrain ${a.size}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "set_terrain_region", description: "39 set_terrain_region – modify bounding box", inputSchema: z.object({ min: z.tuple([z.number(),z.number(),z.number()]), max: z.tuple([z.number(),z.number(),z.number()]), material: z.string().optional().default("Grass"), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("set_terrain_region","--terrain_region", a)}]}), provider:"roblox", execution:"studio"},
  { name: "place_parts", description: "40 place_parts – pattern placement", inputSchema: z.object({ pattern: z.enum(["grid","circle","line"]).default("grid"), count: z.number().default(10), parent: z.string().optional().default("workspace"), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("place_parts",`--place ${a.pattern} x${a.count}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "create_model_from_table", description: "41 create_model_from_table – build model", inputSchema: z.object({ name: z.string(), parts: z.array(z.object({className:z.string(), properties:z.record(z.unknown()).optional()})), parent: z.string().optional().default("workspace"), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("create_model_from_table",`--model ${a.name}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "apply_material", description: "42 apply_material – apply material", inputSchema: z.object({ material: z.string(), region: z.string().optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("apply_material",`--material ${a.material}`, a)}]}), provider:"roblox", execution:"studio"},
  // 43-46 GUI
  { name: "create_ui", description: "43 create_ui – ScreenGui hierarchy", inputSchema: z.object({ name: z.string().default("MyGui"), elements: z.array(z.any()).optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("create_ui",`--ui ${a.name}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "set_ui_property", description: "44 set_ui_property – update UI prop", inputSchema: z.object({ path: z.string(), property: z.string(), value: z.unknown(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("set_ui_property",`--set_ui ${a.path}.${a.property}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "get_ui_tree", description: "45 get_ui_tree – list UI elements", inputSchema: z.object({ projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("get_ui_tree","--ui_tree", a)}]}), provider:"roblox", execution:"studio"},
  { name: "bind_ui_click", description: "46 bind_ui_click – attach click handler", inputSchema: z.object({ path: z.string(), handlerCode: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("bind_ui_click",`--bind ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  // 47-50 Animation
  { name: "create_animation_track", description: "47 create_animation_track – keyframes", inputSchema: z.object({ name: z.string(), keyframes: z.array(z.any()), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("create_animation_track",`--anim ${a.name}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "play_animation", description: "48 play_animation – play on character", inputSchema: z.object({ target: z.string().default("workspace"), animationId: z.string().optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("play_animation","--play_anim", a)}]}), provider:"roblox", execution:"studio"},
  { name: "set_lighting", description: "49 set_lighting – adjust Lighting", inputSchema: z.object({ properties: z.record(z.unknown()), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("set_lighting","--lighting", a)}]}), provider:"roblox", execution:"studio"},
  { name: "add_particle_emitter", description: "50 add_particle_emitter – attach to part", inputSchema: z.object({ path: z.string(), properties: z.record(z.unknown()).optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("add_particle_emitter",`--particle ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  // 51-53 DataStore
  { name: "setup_datastore", description: "51 setup_datastore – define schema", inputSchema: z.object({ name: z.string(), schema: z.record(z.unknown()), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify({datastore:a.name, schema:a.schema}, null,2)}]})},
  { name: "get_datastore_value", description: "52 get_datastore_value – read", inputSchema: z.object({ store: z.string(), key: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("get_datastore_value",`--ds_get ${a.store}:${a.key}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "set_datastore_value", description: "53 set_datastore_value – write", inputSchema: z.object({ store: z.string(), key: z.string(), value: z.unknown(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("set_datastore_value",`--ds_set ${a.store}:${a.key}`, a)}]}), provider:"roblox", execution:"studio"},
  // 54-57 Team
  { name: "export_session_log", description: "54 export_session_log – export JSON (S7)", inputSchema: z.object({ projectId: z.string().optional().default("default"), limit: z.number().optional().default(100) }), handler: async (a)=>{ const logs=teamLog.query({projectId:a.projectId, limit:a.limit}); return {content:[{type:"text", text: JSON.stringify(logs,null,2)}]}; }},
  { name: "replay_session", description: "55 replay_session – replay past session (S7)", inputSchema: z.object({ sessionId: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ const logs=teamLog.query({projectId:a.projectId, limit:200}); return {content:[{type:"text", text: JSON.stringify({sessionId:a.sessionId, logs:logs.slice(0,20)}, null,2)}]}; }},
  { name: "list_sessions", description: "56 list_sessions – list sessions (S7)", inputSchema: z.object({ limit: z.number().optional().default(20) }), handler: async (a)=>{ const logs=teamLog.query({limit:a.limit}); const s=[...new Set(logs.map((l:any)=>l.projectId||"default"))]; return {content:[{type:"text", text: JSON.stringify(s,null,2)}]}; }},
  { name: "compare_sessions", description: "57 compare_sessions – diff two sessions", inputSchema: z.object({ a: z.string(), b: z.string() }), handler: async (a)=>{ const la=teamLog.query({projectId:a.a, limit:50}); const lb=teamLog.query({projectId:a.b, limit:50}); return {content:[{type:"text", text: JSON.stringify({aCount:la.length, bCount:lb.length}, null,2)}]}; }},
  // 58-60 Templates
  { name: "list_templates", description: "58 list_templates – list (S9)", inputSchema: z.object({ category: z.string().optional() }), handler: async (a)=>{ const l=templateStore.list(a.category); return {content:[{type:"text", text: JSON.stringify(l,null,2)}]}; }},
  { name: "apply_template", description: "59 apply_template – apply (S9)", inputSchema: z.object({ id: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ const t=templateStore.get(a.id); if(!t) return {content:[{type:"text", text: JSON.stringify({error:"not found"})}], isError:true}; if(t.code) queueAndWait("run_code", t.code, {templateId:t.id, projectId:a.projectId} as any); return {content:[{type:"text", text: JSON.stringify({applied:true, template:t}, null,2)}]}; }},
  { name: "add_template", description: "60 add_template – user template (S9)", inputSchema: z.object({ id: z.string(), name: z.string(), description: z.string().optional().default(""), category: z.string().optional().default("custom"), code: z.string().optional().default("") }), handler: async (a)=>{ const t=templateStore.create({id:a.id, name:a.name, description:a.description, category:a.category, code:a.code}); return {content:[{type:"text", text: JSON.stringify(t,null,2)}]}; }},
  // 61-64 Misc
  { name: "get_time", description: "61 get_time – current time", inputSchema: z.object({}), handler: async ()=>({content:[{type:"text", text: JSON.stringify({time:new Date().toISOString(), epoch:Date.now()})}]})},
  { name: "send_notification", description: "62 send_notification – Studio notification", inputSchema: z.object({ message: z.string(), type: z.enum(["info","warn","error"]).optional().default("info"), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("send_notification",`--notify ${a.message}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "batch_queue", description: "63 batch_queue – multiple commands", inputSchema: z.object({ commands: z.array(z.object({tool:z.string(), args:z.record(z.unknown()).optional()})), projectId: z.string().optional() }), handler: async (a)=>{ const ids=[]; for(const c of a.commands){ const {id}=queueAndWait(c.tool,c.tool,{...(c.args||{}), projectId:a.projectId}); ids.push(id); } return {content:[{type:"text", text: JSON.stringify({batched:ids.length, ids}, null,2)}]}; }},
  { name: "cancel_command", description: "64 cancel_command – cancel queued", inputSchema: z.object({ id: z.string() }), handler: async (a)=>{ const ok=commandQueue.cancel(a.id); return {content:[{type:"text", text: JSON.stringify({cancelled:ok, id:a.id})}] }; }},
  // 65-111 S-Series
  { name: "train_model", description: "65 train_model – retrain on codebase (S10, offline)", inputSchema: z.object({ projectId: z.string().optional().default("default") }), handler: async (a)=>{ const p=aiTraining.profile(a.projectId); return {content:[{type:"text", text: JSON.stringify({trained:true, profile:p, note:"offline fallback, no API key needed"}, null,2)}]}; }},
  { name: "compile_visual_graph", description: "66 compile_visual_graph – graph→Luau (S11)", inputSchema: z.object({ graph: z.object({nodes:z.array(z.any()), edges:z.array(z.any())}), projectId: z.string().optional() }), handler: async (a)=>{ const r=compileGraph(a.graph as any); if(!r.warnings.length) queueAndWait("run_code", r.luau, {visual:true, projectId:a.projectId} as any); return {content:[{type:"text", text: JSON.stringify(r,null,2)}]}; }},
  { name: "generate_test", description: "67 generate_test – test script (S12)", inputSchema: z.object({ code: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ const t=generateTests(a.code); const h=buildHarness(a.code, t); return {content:[{type:"text", text: JSON.stringify({tests:t, harness:h}, null,2)}]}; }},
  { name: "run_tests", description: "68 run_tests – run all tests (S12)", inputSchema: z.object({ projectId: z.string().optional().default("default") }), handler: async (a)=>{ const {id}=queueAndWait("run_sandbox_tests", "--run_tests", {projectId:a.projectId} as any); return {content:[{type:"text", text: JSON.stringify({queued:true, id})}] }; }},
  { name: "session_users", description: "69 session_users – list active users (S14)", inputSchema: z.object({ projectId: z.string().optional().default("default") }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify(collabManager.list(a.projectId), null,2)}]})},
  { name: "search_asset", description: "70 search_asset – Roblox library (S15)", inputSchema: z.object({ keyword: z.string(), limit: z.number().optional().default(8), category: z.string().optional() }), handler: async (a)=>{ const r=await searchAssets(a.keyword, a.limit, a.category); return {content:[{type:"text", text: JSON.stringify(r,null,2)}]}; }},
  { name: "import_asset", description: "71 import_asset – import by ID (S15)", inputSchema: z.object({ assetId: z.number(), parent: z.string().optional().default("workspace"), projectId: z.string().optional() }), handler: async (a)=>{ const code=importInstruction(a.assetId, a.parent); const {id}=queueAndWait("run_code", code, a as any); return {content:[{type:"text", text: JSON.stringify({queued:true, id}, null,2)}]}; }},
  { name: "report_metrics", description: "72 report_metrics – gameplay metrics (S16)", inputSchema: z.object({ projectId: z.string().optional().default("default"), deathsPerMinute: z.number().optional(), avgFPS: z.number().optional(), killDeathRatio: z.number().optional(), completionTimeSec: z.number().optional(), coinsPerMin: z.number().optional(), activePlayers: z.number().optional() }), handler: async (a)=>{ const {projectId, ...rest}=a; const r=gameplayFeedback.ingest({projectId, timestamp:Date.now(), ...rest} as any); return {content:[{type:"text", text: JSON.stringify(r,null,2)}]}; }},
  { name: "get_metrics", description: "73 get_metrics – recent metrics (S16)", inputSchema: z.object({ projectId: z.string().optional().default("default"), limit: z.number().optional().default(20) }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify(gameplayFeedback.recent(a.projectId, a.limit), null,2)}]})},
  { name: "git_commit", description: "74 git_commit – commit state (S17)", inputSchema: z.object({ message: z.string(), files: z.array(z.string()).optional() }), handler: async (a)=>{ const r=await autoCommit({message:a.message, files:a.files}); return {content:[{type:"text", text: JSON.stringify(r,null,2)}]}; }},
  { name: "git_log", description: "75 git_log – history (S17)", inputSchema: z.object({ limit: z.number().optional().default(10) }), handler: async (a)=>{ const o=await gitLog(a.limit); return {content:[{type:"text", text: o}] }; }},
  { name: "git_rollback", description: "76 git_rollback – revert to commit (S17)", inputSchema: z.object({ commit: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ queueAndWait("undo","--git_rollback",{commit:a.commit, projectId:a.projectId}); return {content:[{type:"text", text: JSON.stringify({rollbackTo:a.commit}, null,2)}]}; }},
  { name: "predict_bug", description: "77 predict_bug – bug prediction (S18)", inputSchema: z.object({ code: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ const rev=reviewLuau(a.code); const bugs=rev.issues.filter((i:any)=> i.severity==="high"); return {content:[{type:"text", text: JSON.stringify({predictions:bugs, risk: bugs.length>2?"high":bugs.length?"medium":"low"}, null,2)}]}; }},
  { name: "plan_game", description: "78 plan_game – GDD from description (S19)", inputSchema: z.object({ prompt: z.string() }), handler: async (a)=>{ const g=generateGDD(a.prompt); return {content:[{type:"text", text: JSON.stringify(g,null,2)}]}; }},
  { name: "execute_plan", description: "79 execute_plan – queue plan steps (S19)", inputSchema: z.object({ prompt: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ const p=planFromPrompt(a.prompt); const ids=[]; for(const s of p.steps){ const {id}=queueAndWait("run_code", s.codePreview||`--plan ${s.title}`, {projectId:a.projectId} as any); ids.push(id); } return {content:[{type:"text", text: JSON.stringify({plan:p, queued:ids}, null,2)}]}; }},
  { name: "review_code", description: "80 review_code – code review (S20)", inputSchema: z.object({ code: z.string() }), handler: async (a)=>{ const rev=reviewLuau(a.code); const plan=refactoringPlan(a.code); return {content:[{type:"text", text: JSON.stringify({...rev, refactoringPlan:plan}, null,2)}]}; }},
  { name: "refactor_code", description: "81 refactor_code – apply refactor (S20)", inputSchema: z.object({ code: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ const h=healCode(a.code,"refactor"); const f=h.fixed||a.code; queueAndWait("run_code", f, {projectId:a.projectId} as any); return {content:[{type:"text", text: JSON.stringify(h,null,2)}]}; }},
  { name: "generate_asset", description: "82 generate_asset – text→3D/texture (S21 procedural, no key)", inputSchema: z.object({ prompt: z.string(), kind: z.enum(["model","texture"]).optional().default("model"), projectId: z.string().optional() }), handler: async (a)=>{ const r=await generateAsset(a.prompt, a.kind as any); if(r.ok) queueAndWait("run_code", r.code, {prompt:a.prompt, projectId:a.projectId} as any); return {content:[{type:"text", text: JSON.stringify(r,null,2)}]}; }},
  { name: "optimize_performance", description: "83 optimize_performance – auto-optimizer (S22)", inputSchema: z.object({ projectId: z.string().optional().default("default"), snapshot: z.string().optional() }), handler: async (a)=>{ const r=autoOptimize(a.snapshot, a.projectId); return {content:[{type:"text", text: JSON.stringify(r,null,2)}]}; }},
  { name: "report_analytics", description: "84 report_analytics – player analytics (S23)", inputSchema: z.object({ projectId: z.string().optional().default("default"), event: z.string().optional(), value: z.number().optional(), metadata: z.record(z.unknown()).optional() }), handler: async (a)=>{ teamLog.append("info", a.projectId, "analytics", a.event||"report", a); return {content:[{type:"text", text: JSON.stringify(analyticsEngine.report(a.projectId), null,2)}]}; }},
  { name: "get_analytics", description: "85 get_analytics – summaries (S23)", inputSchema: z.object({ projectId: z.string().optional().default("default") }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify(analyticsEngine.report(a.projectId), null,2)}]})},
  { name: "suggest_design", description: "86 suggest_design – recommendations (S23)", inputSchema: z.object({ projectId: z.string().optional().default("default") }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify(analyticsEngine.suggest(a.projectId), null,2)}]})},
  { name: "list_plugins", description: "87 list_plugins – loaded plugins (S25)", inputSchema: z.object({}), handler: async ()=>({content:[{type:"text", text: JSON.stringify({plugins:["rolink-core","selfHeal","perfTracker"], count:3}, null,2)}]})},
  { name: "load_plugin", description: "88 load_plugin – load/reload (S25)", inputSchema: z.object({ name: z.string(), code: z.string().optional() }), handler: async (a)=>{ if(a.code){ const v=validateLuau(a.code); if(!v.ok) return {content:[{type:"text", text: JSON.stringify(v,null,2)}], isError:true}; } return {content:[{type:"text", text: JSON.stringify({loaded:true, plugin:a.name}, null,2)}]}; }},
  { name: "set_breakpoint", description: "89 set_breakpoint – breakpoint (S28)", inputSchema: z.object({ path: z.string(), line: z.number(), condition: z.string().optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("set_breakpoint",`--bp ${a.path}:${a.line}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "remove_breakpoint", description: "90 remove_breakpoint – remove (S28)", inputSchema: z.object({ path: z.string(), line: z.number(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("remove_breakpoint",`--rmbp ${a.path}:${a.line}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "watch_variable", description: "91 watch_variable – watch (S28)", inputSchema: z.object({ path: z.string(), variable: z.string(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("watch_variable",`--watch ${a.path} ${a.variable}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "step_through", description: "92 step_through – step (S28)", inputSchema: z.object({ path: z.string(), steps: z.number().optional().default(1), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("step_through",`--step ${a.path}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "continue_execution", description: "93 continue_execution – resume (S28)", inputSchema: z.object({ path: z.string().optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("continue_execution","--continue", a)}]}), provider:"roblox", execution:"studio"},
  { name: "generate_level", description: "94 generate_level – constraints (S29)", inputSchema: z.object({ prompt: z.string().optional().default("obby"), constraints: z.record(z.unknown()).optional(), projectId: z.string().optional() }), handler: async (a)=>{ const code=`-- S29 ${a.prompt}`; const {id}=queueAndWait("run_code", code, {prompt:a.prompt, projectId:a.projectId} as any); return {content:[{type:"text", text: JSON.stringify({queued:true, id, prompt:a.prompt}, null,2)}]}; }},
  { name: "get_projects", description: "95 get_projects – list (S30)", inputSchema: z.object({}), handler: async ()=>({content:[{type:"text", text: JSON.stringify({projects:["default","lobby","obby"], active:"default"}, null,2)}]})},
  { name: "switch_project", description: "96 switch_project – switch (S30)", inputSchema: z.object({ projectId: z.string() }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify({switched:true, projectId:a.projectId}, null,2)}]})},
  { name: "create_project", description: "97 create_project – create (S30)", inputSchema: z.object({ projectId: z.string(), template: z.string().optional() }), handler: async (a)=>{ if(a.template){ const t=templateStore.get(a.template); if(t?.code) queueAndWait("run_code", t.code, {projectId:a.projectId} as any); } return {content:[{type:"text", text: JSON.stringify({created:true, projectId:a.projectId}, null,2)}]}; }},
  { name: "get_suggestions", description: "98 get_suggestions – predictive (S33)", inputSchema: z.object({ context: z.string().optional(), projectId: z.string().optional().default("default") }), handler: async (a)=>{ const r=teamLog.query({projectId:a.projectId, limit:5}); const s=r.length? ["run_code","take_snapshot"] : ["create_instance","execute_luau"]; return {content:[{type:"text", text: JSON.stringify({suggestions:s}, null,2)}]}; }},
  { name: "run_playtest", description: "99 run_playtest – playtest (S35)", inputSchema: z.object({ projectId: z.string().optional().default("default"), durationSec: z.number().optional().default(5) }), handler: async (a)=>({content:[{type:"text", text: studioQueue("simulate_ticks",`--playtest ${a.durationSec}s`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "export_project", description: "100 export_project – archive (S37)", inputSchema: z.object({ projectId: z.string().optional().default("default") }), handler: async (a)=>{ const snap=buildContext({projectId:a.projectId, snapshot:""}); return {content:[{type:"text", text: JSON.stringify({exported:true, archive: Buffer.from(JSON.stringify(snap)).toString("base64").slice(0,200)}, null,2)}]}; }},
  { name: "import_project", description: "101 import_project – import archive (S37)", inputSchema: z.object({ archive: z.string(), projectId: z.string().optional() }), handler: async (a)=>{ try{ const d=JSON.parse(Buffer.from(a.archive, "base64").toString()); queueAndWait("run_code","--import",{projectId:a.projectId} as any); return {content:[{type:"text", text: JSON.stringify({imported:true, preview:String(JSON.stringify(d).slice(0,200))}, null,2)}]};}catch(e:any){ return {content:[{type:"text", text: JSON.stringify({error:String(e.message)})}], isError:true}; }}},
  { name: "generate_quest", description: "102 generate_quest – quests (S38)", inputSchema: z.object({ theme: z.string().optional().default("adventure"), difficulty: z.string().optional().default("medium"), projectId: z.string().optional() }), handler: async (a)=>{ const q={id:`q_${Date.now()}`, theme:a.theme, difficulty:a.difficulty, objectives:["Talk to NPC",`Collect 3 ${a.theme} items`], rewards:{coins:100}}; queueAndWait("run_code",`--quest ${q.id}`,{projectId:a.projectId} as any); return {content:[{type:"text", text: JSON.stringify(q,null,2)}]}; }},
  { name: "simulate_economy", description: "103 simulate_economy – sim (S40)", inputSchema: z.object({ config: z.record(z.unknown()).optional(), iterations: z.number().optional().default(1000), projectId: z.string().optional() }), handler: async (a)=>{ const inf=(Math.random()*0.04-0.02).toFixed(4); return {content:[{type:"text", text: JSON.stringify({iterations:a.iterations, inflation:inf, balance:"stable"}, null,2)}]}; }},
  { name: "suggest_balance", description: "104 suggest_balance – balance (S40)", inputSchema: z.object({ projectId: z.string().optional().default("default") }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify({suggestions: analyticsEngine.suggest(a.projectId)}, null,2)}]})},
  { name: "explain_code", description: "105 explain_code – explain (S43 offline)", inputSchema: z.object({ code: z.string().optional(), path: z.string().optional(), projectId: z.string().optional() }), handler: async (a)=>{ const src=a.code||a.path||""; const rev=reviewLuau(src); return {content:[{type:"text", text: JSON.stringify({explanation:`Script ${a.path||"inline"}`, issues:rev.issues, mermaid:"graph TD; A-->B"}, null,2)}]}; }},
  { name: "learning_mode", description: "106 learning_mode – toggle (S43)", inputSchema: z.object({ enabled: z.boolean().optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: JSON.stringify({learningMode:a.enabled??true}, null,2)}]})},
  { name: "adjust_difficulty", description: "107 adjust_difficulty – DDA (S45)", inputSchema: z.object({ projectId: z.string().optional().default("default"), metrics: z.record(z.unknown()).optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("adjust_difficulty","--dda_adjust", a)}]}), provider:"roblox", execution:"studio"},
  { name: "set_difficulty_profile", description: "108 set_difficulty_profile – mode (S45)", inputSchema: z.object({ profile: z.enum(["easy","medium","hard","adaptive"]), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("set_difficulty_profile",`--dda_profile ${a.profile}`, a)}]}), provider:"roblox", execution:"studio"},
  { name: "generate_sound", description: "109 generate_sound – audio (S48 procedural, no key)", inputSchema: z.object({ prompt: z.string(), type: z.enum(["sfx","music","voice"]).optional().default("sfx"), projectId: z.string().optional() }), handler: async (a)=>{ const p=`Assets/Audio/${a.prompt.replace(/\s+/g,"_")}.ogg`; const code=`local s=Instance.new("Sound"); s.SoundId="rbxassetid://0"; s.Parent=workspace`; queueAndWait("run_code", code, {sound:true, prompt:a.prompt, projectId:a.projectId} as any); return {content:[{type:"text", text: JSON.stringify({generated:true, prompt:a.prompt, path:p, note:"procedural, no key"}, null,2)}]}; }},
  { name: "generate_sound_pack", description: "110 generate_sound_pack – multiple (S48)", inputSchema: z.object({ prompt: z.string(), count: z.number().optional().default(3), type: z.enum(["sfx","music","voice"]).optional().default("sfx") }), handler: async (a)=>{ const packs=Array.from({length:a.count||3}, (_,i)=>({prompt:`${a.prompt} ${i+1}`, path:`Assets/Audio/${i}.ogg`})); return {content:[{type:"text", text: JSON.stringify({pack:packs}, null,2)}]}; }},
  { name: "play_sound", description: "111 play_sound – play (S48)", inputSchema: z.object({ path: z.string().optional().default("workspace"), soundId: z.string().optional(), projectId: z.string().optional() }), handler: async (a)=>({content:[{type:"text", text: studioQueue("play_sound","--play_sound", a)}]}), provider:"roblox", execution:"studio"},
];
